clean:
	rm -f *.log

#certificate:
	#openssl req -nodes -x509 -newkey rsa:4096 -sha256 -keyout example.key -out example.crt -subj "/CN=example.com" -days 3650
	#cat example.key example.crt > certificate.pem

	#openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
	#openssl x509 -text -noout -in certificate.pem
	#openssl pkcs12 -inkey key.pem -in certificate.pem -export -out certificate.p12
	#openssl pkcs12 -in certificate.p12 -noout -info
